apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-lab
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/kashya2/platform-lab.git
              revision: main
              files:
                - path: apps/*/argocd.yaml
          - list:
              elements:
                - name: kind
                  server: https://kubernetes.default.svc
                  namespace: default
  template:
    metadata:
      name: '{{name}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/kashya2/platform-lab.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
