apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-lab
  namespace: argocd
spec:
  goTemplate: true

  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/kashya2/platform-lab.git
              revision: main
              files:
                - path: apps/*/argocd.yaml
          - list:
              elements:
                - name: kind
                  server: https://kubernetes.default.svc

  template:
    metadata:
      name: "{{ .path.basename }}-{{ .name }}"
      namespace: argocd
      labels:
        service: "{{ .path.basename }}"
        environment: "{{ .labels.environment }}"
        provider: "{{ .labels.provider }}"

    spec:
      project: '{{ .argocd.project | default "default" }}'

      destination:
        server: "{{ .server }}"
        namespace: "{{ .argocd.namespace | default .path.basename }}"

      source:
        repoURL: '{{ .argocd.source.repoURL | default "https://github.com/kashya2/platform-lab.git" }}'
        targetRevision: '{{ .argocd.source.targetRevision | default "main" }}'
        path: '{{ .argocd.source.path | default .path.path }}'

  templatePatch: |
    spec:
      {{- if (ne ((((.argocd).syncPolicy).automated).enabled) false) }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      {{- end }}
      syncOptions:
        - CreateNamespace=true
